## Tensor
- 텐서는 배열이나 행렬과 유사한 자료구조이다.
- Pytorch에서는 텐서를 사용하여 모델의 입력(input)과 출력(output), 모델의 매개변수를 부호화(encode)한다.
- GPU를 이용하여 가속화하여 연산할 수 있다.
- 자동 미분에 최적화 되었다.

In [8]:
import torch
import numpy as np

print(f"torch:{torch.__version__}")
print(f"np:{np.__version__}")

torch:1.13.1+cu117
np:1.26.2


## 텐서의 초기화


In [10]:
## 데이터로 부터 직접 만들기
data = [    [1,2],
            [3,4]]
x_data = torch.tensor(data)
print(x_data)
## 데이터의 자료형은 자동으로 유추한다.

tensor([[1, 2],
        [3, 4]])


In [12]:
## numpy로 부터 초기화
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [18]:
## 다른 tensor로 부터 생성
x_ones = torch.ones_like(x_data) # x_data의 속성(차원정보/data type(dtype)을 유지함
print(x_ones)

x_rand = torch.rand_like(x_data, dtype=torch.float32) #rand의 경우 x_data의 차원정보만 덮어씀
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.9024, 0.1748],
        [0.5865, 0.1016]])


## 무작위나 상수값 쓰기
- shape은 텐서의 차원정보를 나타내며 자료형은 튜플. 

In [21]:


shape = (2,3,) # 3개 요소를 가진 총 2개의 정보

rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"{rand_tensor}\n{ones_tensor}\n{zeros_tensor}\n")

tensor([[0.3338, 0.2309, 0.1046],
        [0.1566, 0.3407, 0.2690]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])



## 텐서의 속성 (Attribute)
- 텐서의 속성은 1. 텐서의 모양, 2. 자료형 및 어느장치에 저장되는지를 나타낸다

In [30]:
tensor = torch.rand((3,4))

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## 텐서의 연산
- 전치, 인덱싱, 슬라이싱, 수학 계산, 선형 대수, 임의 샘플링 등 연산을 수행할 수 있다.
- GPU에서도 가능함.
- 기본적 텐서는 cpu에 생성되며 .to 메서드를 사용 시 GPU로 텐서를 명시적 이동 가능
- 장치들 간 큰 텐서의 값을 이동 시키는 것은 공간,시간적 비용이 크다.

In [31]:
# GPU가 존재하면 텐서를 이동합니다
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [36]:
# Numpy식 텐서 연산

tensor = torch.ones(4,4)

print(f"1row = {tensor[0]}") # 0행 출력
print(f"1col = {tensor[:,0]}") # 0열 출력
print(f"last col = {tensor[..., -1]}") # 마지막열(-1번째열) 출력
tensor[:,1] = 0 # 1열 0으로 초기화
print(tensor)

1row = tensor([1., 1., 1., 1.])
1col = tensor([1., 1., 1., 1.])
last col = tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [55]:
# 텐서합치기
# 위 아래로 합치기. dim = 0, vstack((x,y)), row_stack
t_down = torch.cat([tensor, tensor, tensor], dim = 0)
print(t_down)

# 옆으로 합치기. dim = 1, hstack((x,y)), column_stack
t_next = torch.cat([tensor, tensor, tensor], dim = 1)
print(t_next)

# 새로운 차원 추가. dim = 0은 두개의 텐서를 위아래로 차원 추가. dim = 1은 새로운 텐서를 추가해서 좌우로 합쳐줌
t_stack_0 = torch.stack([tensor, tensor], dim = 0)
print(t_stack_0)
t_stack_1 = torch.stack([tensor, tensor], dim = 1)
print(t_stack_1)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
tensor([[[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]]])
tensor([[[1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.]]])


In [57]:
## 산술 연산
## 두 텐서간의 행렬 곱(matrix multiplication)을 계산합니다.
## y1,y2,y3은 다 같은값이다.
## .T는 전치행렬으로 가져온다.
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

## 요소곱 (element - wise product, z1=z2=z3)
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out = z3)

print(y1, y2, y3, z1, z2 ,z3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [62]:
## 단일요소텐서
## 텐서의 모든 값을 하나로 단일 집계하여 요소가 하나인 텐서의 경우, item()을 사용하여 python 숫자값으로 변환 가능함

agg = tensor.sum()
agg_item = agg.item()

print(
    tensor.sum(),
    tensor.sum().item(),
    type(tensor.sum()),
    type(tensor.sum().item())
)

tensor(12.) 12.0 <class 'torch.Tensor'> <class 'float'>


In [63]:
## 바꿔치기 연산
## 연산 결과를 피연산자에 저장하는 연산. _접미사가 붙음
## x.copy_(y)나 x._t()는 x를 변경함

print(f"{tensor}")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [73]:
## Numpy변환
## cPU 상의 텐서와 NumPy 배열은 메모리 공간을 공유하기 때문에, 하나를 변경하면 다른 하나도 변경됩니다.
## 그 반대의 경우에도 변경 사항이 공유됨
t = torch.ones(5)
t = t.to("cuda")
n = t.numpy()

print(t,n)

t.add_(1)
print(t,n)

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.